services:
  db:
    image: postgres:16
    container_name: pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D0nkeyK0ng!
      POSTGRES_DB: birds_eye
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_volume: